### ISSUE TITLE
Configurable text for skip button

### ISSUE THREAD

**Issue by diegoot-dev** [ArteGEIE/videojs-vast#52]
Please add option for configurable text for skip button.

**Comment by Coralielm** [comment]
Hi @diegoot-dev,

Thank you for your feedback.

**Comment by Coralielm** [comment]
@diegoot-dev could you please provide more informations?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
